# For more information: https://laravel.com/docs/sail
version: '3'
services:
    soketi:
        container_name: soketi
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        build: 
            context: .
            dockerfile: DockerFile
        environment:
        # all enviroment variables -> https://github.com/soketi/soketi/blob/master/src/cli/cli.ts & https://github.com/soketi/soketi/issues/354#issuecomment-1056631479
            DEFAULT_APP_ID: 'soketi_id'
            DEFAULT_APP_KEY: 'soketi_key'
            DEFAULT_APP_SECRET: 'soketi_secret'
            DEBUG: '1'
            METRICS_SERVER_PORT: '9601'
            DEFAULT_APP_ENABLE_CLIENT_MESSAGES: true
            
        ports:
            - 6001:6001
            - 9601:9601